### ISSUE TITLE
Missing lazy-prereq support?

### ISSUE THREAD

**Issue by gitster** [felipec/sharness#53]
As I saw v1.0 announcement, I took a brief look at this package. It does look familiar ;-) but seems to lack quite a lot of things that happened in not-so-recent-past. It seems that the codebase was forked long time ago, long before we split t/test-lib.sh and t/test-lib-funcitons.sh (the latter of which is more generic part, which sharness would want to be tracking)?

**Comment by chriscool** [comment]
Yeah true, it was forked in 2011 and there are still some missing features.
I will take a look at tracking test-lib-functions.sh.
Thanks!

**Comment by felipec** [comment]
While having `lazy-prereq` support could be useful in certain scenarios, the complexity necessary support that doesn't seem to be warranted or necessary in any project other than `git` upstream.

In fact, even in `git` upstream it could be argued that `lazy-prereq` is overengineering, as the same functionality can be achieved through other means.

For example, instead of the current `lazy-prereq` for `PIPE`:

```
test_lazy_prereq PIPE '
	test_have_prereq !MINGW,!CYGWIN &&
	rm -f testfifo && mkfifo testfifo
'
```

Exactly the same behavior can be achieved through a normal prereq that only the four test files that need it include.

The change would look something like:

```diff
diff --git a/t/t0008-ignores.sh b/t/t0008-ignores.sh
index c70d11bc91..b16c1d3d42 100755
--- a/t/t0008-ignores.sh
+++ b/t/t0008-ignores.sh
@@ -5,6 +5,7 @@ test_description=check-ignore
 TEST_PASSES_SANITIZE_LEAK=true
 TEST_CREATE_REPO_NO_TEMPLATE=1
 . ./test-lib.sh
+. "$TEST_DIRECTORY"/test-lib-pipe.sh
 
 init_vars () {
 	global_excludes="global-excludes"
diff --git a/t/t1400-update-ref.sh b/t/t1400-update-ref.sh
index 4d66cd7f4a..208cbad2e2 100755
--- a/t/t1400-update-ref.sh
+++ b/t/t1400-update-ref.sh
@@ -5,6 +5,7 @@
 
 test_description='Test git update-ref and basic ref logging'
 . ./test-lib.sh
+. "$TEST_DIRECTORY"/test-lib-pipe.sh
 
 Z=$ZERO_OID
 
diff --git a/t/t4056-diff-order.sh b/t/t4056-diff-order.sh
index aec1d9d1b4..edb8d47016 100755
--- a/t/t4056-diff-order.sh
+++ b/t/t4056-diff-order.sh
@@ -6,6 +6,7 @@ GIT_TEST_DEFAULT_INITIAL_BRANCH_NAME=main
 export GIT_TEST_DEFAULT_INITIAL_BRANCH_NAME
 
 . ./test-lib.sh
+. "$TEST_DIRECTORY"/test-lib-pipe.sh
 
 create_files () {
 	echo "$1" >a.h &&
diff --git a/t/t9300-fast-import.sh b/t/t9300-fast-import.sh
index ac237a1f90..4ae2dc7f1b 100755
--- a/t/t9300-fast-import.sh
+++ b/t/t9300-fast-import.sh
@@ -9,6 +9,7 @@ export GIT_TEST_DEFAULT_INITIAL_BRANCH_NAME
 
 . ./test-lib.sh
 . "$TEST_DIRECTORY"/lib-diff.sh ;# test-lib chdir's into trash
+. "$TEST_DIRECTORY"/test-lib-pipe.sh
 
 verify_packs () {
 	for p in .git/objects/pack/*.pack
diff --git a/t/test-lib-pipe.sh b/t/test-lib-pipe.sh
new file mode 100644
index 0000000000..926ff49988
--- /dev/null
+++ b/t/test-lib-pipe.sh
@@ -0,0 +1,3 @@
+test_have_prereq !MINGW,!CYGWIN &&
+rm -f testfifo && mkfifo testfifo &&
+test_set_prereq PIPE
diff --git a/t/test-lib.sh b/t/test-lib.sh
index 293caf0f20..2105c05ed5 100644
--- a/t/test-lib.sh
+++ b/t/test-lib.sh
@@ -1760,12 +1760,6 @@ then
 	export GIT_TEST_CHECK_CACHE_TREE
 fi
 
-test_lazy_prereq PIPE '
-	# test whether the filesystem supports FIFOs
-	test_have_prereq !MINGW,!CYGWIN &&
-	rm -f testfifo && mkfifo testfifo
-'
-
 test_lazy_prereq SYMLINKS '
 	# test whether the filesystem supports symbolic links
 	ln -s x y && test -h y
```

I think it's better and simpler to modify only the test files that need this check, instead of doing overengineering of the testing framework which affects thousands of test files just in the `git` upstream project.

Moreover, nobody else other than `git` upstream seems to be interested in this feature.

If `git` upstream is ever interested in using sharness as their testing framework, or discussing a proper way to implement this functionality, this issue could be reopened and reconsidered.
